### PR TITLE
Fixed inconsistencies and typos in examples

### PR DESCRIPTION
**Pull request by birnbaum**
null

---
[Documentation of `scenario-formatting`](https://diselab.github.io/marvis/scenario-formatting)

### CODE REVIEW

**Comment by lpirl** [comment]
LGTM although I am not sure why you removed the shebangs.

**Comment by birnbaum** [comment]
I removed the shebangs because they were present in some files and not in others. I don't think it makes sense to maintain different ways to execute a program, if the docs say use `python ...`, I think it's nice if that's the one and only way.

**Comment by lpirl** [comment]
fair enough and too unimportant to discuss in detail :)

**Comment by arneboockmeyer** [comment]
@birnbaum Due to the current github actions (see this line: https://github.com/diselab/marvis/blob/master/.github/workflows/main.yml#L26) we either need shebangs or need to change the actions to `python3 ./basic_example.py`. If have a minor preference for the last option.
Otherwise the test are failing.

**Comment by lpirl** [comment]
Vote for shebangs. I see the point of @birnbaum – and feel the OCD regarding inconsistencies :) – at the same time, I don't think that it's a big deal to have different ways of executing our scripts. Our target audience should be able to deal with this.

**Pull request merged**
