### PR TITLE
improved SUMO documentation in Readme

### PR DESCRIPTION
**Pull request by birnbaum**
To discuss:
- Running the experiment in the Docker container results in `ModuleNotFoundError: No module named 'traci'`
- After manually installing TraCi I get: `AttributeError: type object 'wifi.YansWifiPhyHelper' has no attribute 'Default'` in `marvis/channel/wifi.py` 

Maybe someone has an idea what's the best way to fix this, I'm not familiar with the SUMO and ns3 code

---
[Documentation of `fix-sumo-scenario`](https://diselab.github.io/marvis/fix-sumo-scenario)

### CODE REVIEW

**Comment by lpirl** [comment]
LGTM

**Comment by lpirl** [comment]
> * Running the experiment in the Docker container results in `ModuleNotFoundError: No module named 'traci'`
> * After manually installing TraCi I get: `AttributeError: type object 'wifi.YansWifiPhyHelper' has no attribute 'Default'` in `marvis/channel/wifi.py`

Hm running the Docker container (on Debian Bullseye) and installing `sumo` and `sumo` tools lets me execute the `sumo_example.py` without any problems. Do you have more details on how to reproduce the error you experienced?

**Comment by birnbaum** [comment]
Thanks for trying it, I think the error was on my side. I purged all Docker data and now it seems to work (or at least not crash), sorry! Also, it seems like my local sumo installation is not loading the scenario files properly until I open `localhost:8813` once in the browser (i.e. a normal GET request).

Now with a running sumo scenario, if I execute the application I get:
```
...
20:51:30 marvis.node.docker               INFO     Building docker image: ./docker/sumo/Dockerfile
20:51:30 marvis.node.docker               INFO     Starting docker container: train
20:51:30 train                            ERROR    Device "ns3-eth0" does not exist.
20:51:30 marvis.context                   INFO     Cleanup 1 items
20:51:30 marvis.node.docker               INFO     Stopping docker container: train
```

With the tracelog:
```
Traceback (most recent call last):
  File "sumo_example.py", line 35, in <module>
    parser.run(main)
  File "/usr/local/lib/python3.7/site-packages/marvis/argparse.py", line 58, in run
    main(**args)
  File "sumo_example.py", line 30, in main
    sim.simulate(simulation_time=30)
  File "/usr/local/lib/python3.7/site-packages/marvis/simulation.py", line 158, in simulate
    self.__simulate(simulation_time)
  File "/usr/local/lib/python3.7/site-packages/marvis/simulation.py", line 177, in __simulate
    self.prepare()
  File "/usr/local/lib/python3.7/site-packages/marvis/util.py", line 19, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/marvis/simulation.py", line 131, in prepare
    node.prepare(self)
  File "/usr/local/lib/python3.7/site-packages/marvis/node/docker.py", line 148, in prepare
    self.setup_host_interfaces()
  File "/usr/local/lib/python3.7/site-packages/marvis/node/docker.py", line 237, in setup_host_interfaces
    interface.setup_bridge()
  File "/usr/local/lib/python3.7/site-packages/marvis/interface.py", line 114, in setup_bridge
    ipr.link('add', ifname=self.bridge_name, kind='bridge')
  File "/usr/local/lib/python3.7/site-packages/pyroute2/iproute/linux.py", line 1394, in link
    msg_flags=msg_flags)
  File "/usr/local/lib/python3.7/site-packages/pyroute2/netlink/nlsocket.py", line 391, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/local/lib/python3.7/site-packages/pyroute2/netlink/nlsocket.py", line 884, in nlm_request
    callback=callback):
  File "/usr/local/lib/python3.7/site-packages/pyroute2/netlink/nlsocket.py", line 394, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python3.7/site-packages/pyroute2/netlink/nlsocket.py", line 719, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')
```

Any idea what's going on? I'm running the container and starting the application exactly as noted in the Readme. Thanks!

**Comment by arneboockmeyer** [comment]
@birnbaum The problem is that the veth pairs get not cleaned up perfectly. This commit: https://github.com/diselab/marvis/pull/14/commits/554da2202457303c2b63d621d5fffc5f49bd4176 of the PR https://github.com/diselab/marvis/pull/14 should fix this. Since the PR is much bigger than just the small commit, it could be worth it to cherry pick that commit and verify that it fixes your issue. Afterwards we could merge that one separately.

**Pull request merged**
